### ISSUE TITLE
Auto-restart jobs on user-specified error conditions

### ISSUE THREAD

**Issue by albertz** [rwth-i6/sisyphus#179] opened 2024-02-05 07:52 UTC
There are certain errors which we frequently see in our cluster, where I want that my job in error state is automatically restarted.

Examples:

* `RuntimeError: cuFFT error: CUFFT_INTERNAL_ERROR`
* (other similar CUDA errors)
* CUDA OOM or CPU OOM, *and* it trained at least one epoch since last run

In that case, currently I just manually delete the `error` and `submit_log`.

I want some way in the Sisyphus that the manager can automatically do that for me.

How?

I'm not sure. Maybe some custom user callback once a job gets into error state? One suggestion was made in #204:
```python
def task_exit(
    *,
    job: tk.Job,
    task_name: str,
    success: bool,
    engine_info: Any,  # last engine_info from submit_log
    usage: Any,  # usage from usage log
    call: List[str],  # actual call after worker_wrapper
    # log: str,  # could also feed in the log output here? depending on the job very memory intensive...
) -> Optional[bool]: ...
```

Additionally, sometimes I want to temporarily add some cluster nodes to the exclude list, maybe for 1 day or so, when they fail again and again with the same CUDA error. This should also be possible somehow.

**Comment by NeoLegends** [comment] 2024-08-14 12:44
Ah, this is a duplicate of/very similar to #204

**Closed** 2024-09-23 15:29 UTC
